name = "spqr"
defaultTargets = ["Spqr"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "Spqr"

[[lean_exe]]
name = "dump_lean"
root = "DumpLean"

[[lean_exe]]
name = "dump_planar_lean"
root = "DumpPlanarLean"

[[lean_exe]]
name = "check_planar_lean"
root = "CheckPlanarLean"
